# Generated by Django 6.0.3 on 2026-10-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_emailtemplate_subject_profile_default_email_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_application_year',
        ),
    ]
