# Generated by Django 6.0.3 on 2026-10-10 13:00

from django.db import migrations, models
from django.db.models import F


def backfill_sent_reminders(apps, schema_editor):
    """Treat reminders already emailed as delivered and read, so existing users
    don't get a notification bubble full of old reminders."""
    Reminder = apps.get_model("profiles", "Reminder")
    Reminder.objects.filter(is_sent=True).update(
        delivered_at=F("remind_at"), read_at=F("remind_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_profile_current_application_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_sent_reminders, migrations.RunPython.noop),
    ]
