# Generated by Django 6.0.3 on 2026-10-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0014_applicationseason_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="application_year_value",
        ),
        migrations.AddField(
            model_name="application",
            name="sent_message_id",
            field=models.CharField(blank=True, db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPLIED", "Applied"),
                    ("IN_DISCUSSION", "In discussion"),
                    ("REJECTED", "Rejected"),
                    ("IGNORED", "Ignored"),
                    ("ACCEPTED", "Accepted"),
                    ("POSTPONED", "Postponed"),
                    ("CANCELLED", "Cancelled"),
                    ("OTHER", "Other"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="InboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message_id", models.CharField(max_length=512, unique=True)),
                ("from_address", models.CharField(max_length=320)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("body", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "suggested_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPLIED", "Applied"),
                            ("IN_DISCUSSION", "In discussion"),
                            ("REJECTED", "Rejected"),
                            ("IGNORED", "Ignored"),
                            ("ACCEPTED", "Accepted"),
                            ("POSTPONED", "Postponed"),
                            ("CANCELLED", "Cancelled"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("APPROVED", "Approved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_emails",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
