# Generated by Django 6.0.3 on 2026-10-07 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_profile_from_application(apps, schema_editor):
    InboundEmail = apps.get_model("applications", "InboundEmail")
    for email in InboundEmail.objects.select_related("application"):
        email.profile_id = email.application.profile_id
        email.save(update_fields=["profile"])


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0015_inbound_email"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundemail",
            name="is_auto_reply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inboundemail",
            name="match_method",
            field=models.CharField(
                choices=[
                    ("HEADER", "Reply headers"),
                    ("SENDER", "Sender address"),
                    ("DOMAIN", "Sender domain"),
                    ("NAME", "Organisation name"),
                    ("NONE", "No match"),
                ],
                default="HEADER",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inboundemail",
            name="organisation_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="inboundemail",
            name="organisation_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboundemail",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbound_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPLIED", "Applied"),
                    ("AUTO_REPLY_RECEIVED", "Auto-reply received"),
                    ("IN_DISCUSSION", "In discussion"),
                    ("REJECTED", "Rejected"),
                    ("IGNORED", "Ignored"),
                    ("ACCEPTED", "Accepted"),
                    ("POSTPONED", "Postponed"),
                    ("CANCELLED", "Cancelled"),
                    ("OTHER", "Other"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inboundemail",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbound_emails",
                to="applications.application",
            ),
        ),
        migrations.AlterField(
            model_name="inboundemail",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING_REVIEW", "Pending review"),
                    ("APPROVED", "Approved"),
                    ("DISMISSED", "Dismissed"),
                    ("UNMATCHED", "Unmatched"),
                ],
                default="PENDING_REVIEW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inboundemail",
            name="suggested_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPLIED", "Applied"),
                    ("AUTO_REPLY_RECEIVED", "Auto-reply received"),
                    ("IN_DISCUSSION", "In discussion"),
                    ("REJECTED", "Rejected"),
                    ("IGNORED", "Ignored"),
                    ("ACCEPTED", "Accepted"),
                    ("POSTPONED", "Postponed"),
                    ("CANCELLED", "Cancelled"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(set_profile_from_application, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="inboundemail",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbound_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
