# Generated by Django 6.0.3 on 2026-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0016_inbound_email_unmatched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundemail",
            name="match_method",
            field=models.CharField(
                choices=[
                    ("HEADER", "Reply headers"),
                    ("SENDER", "Sender address"),
                    ("DOMAIN", "Sender domain"),
                    ("NAME", "Organisation name"),
                    ("FORM", "Web form confirmation"),
                    ("NONE", "No match"),
                ],
                default="HEADER",
                max_length=10,
            ),
        ),
    ]
